# Generated by Django 5.0.7 on 2025-09-25 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashier', '0011_venta_cliente_paga'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='numero_transaccion',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Número de Transacción'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='forma_pago',
            field=models.CharField(choices=[('efectivo', 'Efectivo'), ('debito', 'Tarjeta de Débito'), ('credito', 'Tarjeta de Crédito'), ('transferencia', 'Transferencia')], default='efectivo', max_length=20),
        ),
    ]
