# Generated by Django 5.0.7 on 2025-09-26 17:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashier', '0012_venta_numero_transaccion_alter_venta_forma_pago'),
        ('products', '0011_alter_product_permitir_venta_sin_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='banco',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Banco'),
        ),
        migrations.AlterField(
            model_name='ventadetalle',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ventadetalles', to='products.product'),
        ),
    ]
